spring.application.name=Feedback

spring.datasource.url=${FDB_URL}
spring.datasource.username=${FDB_USER}
spring.datasource.password=${FDB_PASSWORD}
spring.datasource.driver=com.mysql.cj.jdbc.Driver



